CREATE TABLE users(
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    first VARCHAR(50),
    last VARCHAR(50),
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Admin user (full access)
CREATE ROLE admin_user WITH LOGIN PASSWORD 'adminpass' SUPERUSER;

-- Editor user (CRUD operations)
CREATE ROLE editor_user WITH LOGIN PASSWORD 'editorpass';

-- Read-only user
CREATE ROLE reader_user WITH LOGIN PASSWORD 'readerpass';

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO editor_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO reader_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON TABLES TO editor_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON TABLES TO reader_user;